"""不依赖硬件的 WindArmor 飞控基础包。"""

from .core import (
    AuthorityGrant,
    AuthorityState,
    AuthorityStateMachine,
    CommandAuthority,
    CommandEnvelopeSequencer,
    FanChannelState,
    FanCommand,
    FanSystemState,
    FlightCommand,
    FlightCommandEnvelope,
    FlightController,
    FlightState,
    ImuState,
    MotorState,
    OwnershipDomain,
    Quaternion,
    SystemState,
    Vector3,
    validate_command_envelope,
)

__all__ = [
    "AuthorityGrant",
    "AuthorityState",
    "AuthorityStateMachine",
    "CommandAuthority",
    "CommandEnvelopeSequencer",
    "FanChannelState",
    "FanCommand",
    "FanSystemState",
    "FlightCommand",
    "FlightCommandEnvelope",
    "FlightController",
    "FlightState",
    "ImuState",
    "MotorState",
    "OwnershipDomain",
    "Quaternion",
    "SystemState",
    "Vector3",
    "validate_command_envelope",
]
